export const VEHICLE_BRANDS: Record<string, string[]> = {
  'Royal Enfield': [
    'Hunter 350',
    'Classic 350',
    'Bullet 350',
    'Meteor 350',
    'Himalayan 450',
    'Scram 411',
    'Continental GT 650',
    'Interceptor 650',
    'Shotgun 650',
    'Super Meteor 650',
    'Guerrilla 450',
  ],
  'Honda': [
    'Activa 6G',
    'Activa 125',
    'Dio 125',
    'Shine 125',
    'SP 125',
    'Unicorn',
    'H\'ness CB350',
    'CB350RS',
    'Hornet 2.0',
    'CB200X',
    'City',
    'Amaze',
    'Elevate',
  ],
  'Yamaha': [
    'MT-15 V2',
    'YZF R15 V4',
    'FZ-S FI',
    'FZ-X',
    'Aerox 155',
    'RayZR 125 Fi',
    'Fascino 125 Fi',
    'R3',
  ],
  'TVS': [
    'Apache RTR 160 4V',
    'Apache RTR 200 4V',
    'Apache RR 310',
    'Raider 125',
    'Jupiter 110',
    'Jupiter 125',
    'Ntorq 125',
    'Ronin',
    'iQube Electric',
    'XL100',
  ],
  'Bajaj': [
    'Pulsar 150',
    'Pulsar NS200',
    'Pulsar N160',
    'Pulsar N250',
    'Pulsar 125',
    'Pulsar RS200',
    'Dominar 400',
    'Dominar 250',
    'Platina 110',
    'CT 125X',
    'Avenger Cruise 220',
    'Chetak Electric',
    'Freedom 125 CNG',
  ],
  'KTM': [
    'Duke 200',
    'Duke 250',
    'Duke 390',
    'RC 200',
    'RC 390',
    '390 Adventure',
    '250 Adventure',
  ],
  'Hero': [
    'Splendor Plus',
    'HF Deluxe',
    'Passion Plus',
    'Glamour',
    'Xpulse 200 4V',
    'Karizma XMR',
    'Mavrick 440',
    'Xtreme 125R',
    'Destini 125',
    'Vida V1 Pro',
  ],
  'Suzuki': [
    'Access 125',
    'Burgman Street',
    'Avenis 125',
    'Gixxer 150',
    'Gixxer SF 250',
    'V-Strom SX',
  ],
  'Ather': [
    '450X',
    '450S',
    '450 Apex',
    'Rizta',
  ],
  'Ola Electric': [
    'S1 Pro Gen 2',
    'S1 Air',
    'S1 X',
  ],
  'Kawasaki': [
    'Ninja 300',
    'Ninja 400',
    'Ninja 500',
    'Ninja 650',
    'Z650',
    'Z900',
    'ZX-6R',
  ],
  'Triumph': [
    'Speed 400',
    'Scrambler 400 X',
    'Trident 660',
    'Tiger 900',
    'Street Triple',
  ],
  'BMW Motorrad': [
    'G 310 R',
    'G 310 GS',
    'G 310 RR',
    'F 900 XR',
    'R 1250 GS',
    'S 1000 RR',
  ],
  'Harley-Davidson': [
    'X440',
    'Nightster',
    'Sportster S',
    'Fat Boy',
  ],
  'Tata': [
    'Nexon',
    'Punch',
    'Harrier',
    'Safari',
    'Tiago',
    'Tigor',
    'Curvv',
    'Nexon EV',
    'Punch EV',
  ],
  'Mahindra': [
    'Thar',
    'Thar Roxx',
    'Scorpio-N',
    'Scorpio Classic',
    'XUV700',
    'XUV 3XO',
    'Bolero',
    'XUV400 EV',
  ],
  'Hyundai': [
    'Creta',
    'Venue',
    'i20',
    'Verna',
    'Exter',
    'Alcazar',
    'Tucson',
    'Ioniq 5',
  ],
  'Maruti Suzuki': [
    'Swift',
    'Baleno',
    'Brezza',
    'Grand Vitara',
    'Fronx',
    'Dzire',
    'Ertiga',
    'Jimny',
  ],
  'Toyota': [
    'Innova Crysta',
    'Innova Hycross',
    'Fortuner',
    'Urban Cruiser Hyryder',
    'Glanza',
    'Hilux',
  ],
  'Kia': [
    'Seltos',
    'Sonet',
    'Carens',
    'EV6',
  ],
  'Other / Custom': [
    'Other Model',
  ],
};

export const BRAND_LIST = Object.keys(VEHICLE_BRANDS);

export function getModelsForBrand(brand: string): string[] {
  return VEHICLE_BRANDS[brand] || ['Other Model'];
}
